### ISSUE TITLE
3.5.0 system prompt errors when upgrading

### ISSUE THREAD

**Issue by Denubis** [Future-House/paper-qa#173]
I've got a basic proof of concept streamlit running paper-qa, and when I upgraded from 3.4.1 it introduced a number of breaking changes. Either asserting `AttributeError: 'OpenAIEmbeddings' object has no attribute 'model_kwargs' or, previously, asserting a problem with the system prompt:
```  File "/home/ubuntu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/paperqa/docs.py", line 448, in process                                                                                                    
    system_prompt=self.prompts.system,                                                                                                                                                                             
                  ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                              
AttributeError: 'PromptCollection' object has no attribute 'system'   ```

Can you double-check your example code in light of 3.5.0? I think... I've probably missed something?

Happy to share my streamlit demo when it's a touch more mature.

**Comment by Danielxpj** [comment]
I'm having AttributeError: 'OpenAIEmbeddings' object has no attribute 'model_kwargs' when calling  result = qa(prompt),  qa = ConversationalRetrievalChain.from_llm(chat, db.as_retriever(), chat_prompt_template) do you think its the same bug?

**Comment by jamesbraza** [comment]
Hello @Denubis, we have just released version 5, which completely outsources all LLM management to https://github.com/BerriAI/litellm.

If your issue persists, please reopen a new issue using `paper-qa>=5`
